spring.application.name=fumetteria
spring.datasource.url=jdbc:postgresql://localhost:5432/comicstore
spring.datasource.username=postgres
spring.datasource.password=postgress
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
logging.file.name=logs/application.log
logging.pattern.console=%d{HH:mm:ss} --- [%t] %-40logger{36} : %msg%n
logging.pattern.file=%d{HH:mm:ss} --- [%t] %-40logger{36} : %msg%n


springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

